name: bidrag-reskontro
ingresses:
  - https://bidrag-reskontro.intern.nav.no
maskinporten:
  url: https://maskinporten.no
env:
  SKATT_URL: https://bidrag-stubs.dev.intern.nav.no #TODO()
  SKATT_HOST: bidrag-stubs.dev.intern.nav.no #TODO()
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0